branchName: short
autoCloseIssue: true
branches:
  - label: docs
    prefix: docs/
  - label: build
    prefix: build/
  - label: refactor
    prefix: refactor/
  - label: chore
    prefix: chore/
  - label: comment
    prefix: comment/
  - label: feat
    prefix: feat/
  - label: fix
    prefix: fix/
  - label: remove
    prefix: remove/
  - label: 'style'
    prefix: style/
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
